/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.skplanet.querycache.cli.thrift;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TGetOperationStatusReq implements org.apache.thrift.TBase<TGetOperationStatusReq, TGetOperationStatusReq._Fields>, java.io.Serializable, Cloneable, Comparable<TGetOperationStatusReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TGetOperationStatusReq");

  private static final org.apache.thrift.protocol.TField OPERATIOIN_HANDLE_FIELD_DESC = new org.apache.thrift.protocol.TField("operatioinHandle", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TGetOperationStatusReqStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TGetOperationStatusReqTupleSchemeFactory());
  }

  public TOperationHandle operatioinHandle; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OPERATIOIN_HANDLE((short)1, "operatioinHandle");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OPERATIOIN_HANDLE
          return OPERATIOIN_HANDLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OPERATIOIN_HANDLE, new org.apache.thrift.meta_data.FieldMetaData("operatioinHandle", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TOperationHandle.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TGetOperationStatusReq.class, metaDataMap);
  }

  public TGetOperationStatusReq() {
  }

  public TGetOperationStatusReq(
    TOperationHandle operatioinHandle)
  {
    this();
    this.operatioinHandle = operatioinHandle;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TGetOperationStatusReq(TGetOperationStatusReq other) {
    if (other.isSetOperatioinHandle()) {
      this.operatioinHandle = new TOperationHandle(other.operatioinHandle);
    }
  }

  public TGetOperationStatusReq deepCopy() {
    return new TGetOperationStatusReq(this);
  }

  @Override
  public void clear() {
    this.operatioinHandle = null;
  }

  public TOperationHandle getOperatioinHandle() {
    return this.operatioinHandle;
  }

  public TGetOperationStatusReq setOperatioinHandle(TOperationHandle operatioinHandle) {
    this.operatioinHandle = operatioinHandle;
    return this;
  }

  public void unsetOperatioinHandle() {
    this.operatioinHandle = null;
  }

  /** Returns true if field operatioinHandle is set (has been assigned a value) and false otherwise */
  public boolean isSetOperatioinHandle() {
    return this.operatioinHandle != null;
  }

  public void setOperatioinHandleIsSet(boolean value) {
    if (!value) {
      this.operatioinHandle = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case OPERATIOIN_HANDLE:
      if (value == null) {
        unsetOperatioinHandle();
      } else {
        setOperatioinHandle((TOperationHandle)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case OPERATIOIN_HANDLE:
      return getOperatioinHandle();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case OPERATIOIN_HANDLE:
      return isSetOperatioinHandle();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TGetOperationStatusReq)
      return this.equals((TGetOperationStatusReq)that);
    return false;
  }

  public boolean equals(TGetOperationStatusReq that) {
    if (that == null)
      return false;

    boolean this_present_operatioinHandle = true && this.isSetOperatioinHandle();
    boolean that_present_operatioinHandle = true && that.isSetOperatioinHandle();
    if (this_present_operatioinHandle || that_present_operatioinHandle) {
      if (!(this_present_operatioinHandle && that_present_operatioinHandle))
        return false;
      if (!this.operatioinHandle.equals(that.operatioinHandle))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_operatioinHandle = true && (isSetOperatioinHandle());
    builder.append(present_operatioinHandle);
    if (present_operatioinHandle)
      builder.append(operatioinHandle);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(TGetOperationStatusReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOperatioinHandle()).compareTo(other.isSetOperatioinHandle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperatioinHandle()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operatioinHandle, other.operatioinHandle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TGetOperationStatusReq(");
    boolean first = true;

    sb.append("operatioinHandle:");
    if (this.operatioinHandle == null) {
      sb.append("null");
    } else {
      sb.append(this.operatioinHandle);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (operatioinHandle == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'operatioinHandle' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (operatioinHandle != null) {
      operatioinHandle.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TGetOperationStatusReqStandardSchemeFactory implements SchemeFactory {
    public TGetOperationStatusReqStandardScheme getScheme() {
      return new TGetOperationStatusReqStandardScheme();
    }
  }

  private static class TGetOperationStatusReqStandardScheme extends StandardScheme<TGetOperationStatusReq> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TGetOperationStatusReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OPERATIOIN_HANDLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.operatioinHandle = new TOperationHandle();
              struct.operatioinHandle.read(iprot);
              struct.setOperatioinHandleIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TGetOperationStatusReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.operatioinHandle != null) {
        oprot.writeFieldBegin(OPERATIOIN_HANDLE_FIELD_DESC);
        struct.operatioinHandle.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TGetOperationStatusReqTupleSchemeFactory implements SchemeFactory {
    public TGetOperationStatusReqTupleScheme getScheme() {
      return new TGetOperationStatusReqTupleScheme();
    }
  }

  private static class TGetOperationStatusReqTupleScheme extends TupleScheme<TGetOperationStatusReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TGetOperationStatusReq struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.operatioinHandle.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TGetOperationStatusReq struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.operatioinHandle = new TOperationHandle();
      struct.operatioinHandle.read(iprot);
      struct.setOperatioinHandleIsSet(true);
    }
  }

}

