/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.skplanet.querycache.cli.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TSessionType implements org.apache.thrift.TEnum {
  SESS_IMPALA_JDBC(0),
  SESS_HIVE_JDBC(1),
  SESS_PHOENIX_JDBC(2),
  SESS_IMPALA_THRIFT(3),
  SESS_HBASE(4),
  SESS_MYSQL_JDBC(5),
  SESS_SPARK_JDBC(6),
  SESS_ORACLE_JDBC(7),
  SESS_DB2_JDBC(8),
  SESS_BERKELEY_JDBC(9),
  SESS_OTHERS(10);

  private final int value;

  private TSessionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSessionType findByValue(int value) { 
    switch (value) {
      case 0:
        return SESS_IMPALA_JDBC;
      case 1:
        return SESS_HIVE_JDBC;
      case 2:
        return SESS_PHOENIX_JDBC;
      case 3:
        return SESS_IMPALA_THRIFT;
      case 4:
        return SESS_HBASE;
      case 5:
        return SESS_MYSQL_JDBC;
      case 6:
        return SESS_SPARK_JDBC;
      case 7:
        return SESS_ORACLE_JDBC;
      case 8:
        return SESS_DB2_JDBC;
      case 9:
        return SESS_BERKELEY_JDBC;
      case 10:
        return SESS_OTHERS;
      default:
        return null;
    }
  }
}
